#!/usr/bin/env bash

# Script to change HP-Uiscan icon
desktopFile="/usr/share/applications/hp-uiscan.desktop"
backupFile="$desktopFile.bak"

# Check if the file exists
if [ -f "$desktopFile" ]; then
    # Create a backup if it doesn't already exist
    if [ ! -f "$backupFile" ]; then
        cp "$desktopFile" "$backupFile"
    fi
    # Modify the icon
    sed -i 's/^Icon=.*/Icon=hp_logo/' "$desktopFile"
fi
